// src/countriesData.js

const countries = [
  { name: 'Afghanistan', flag: '🇦🇫', value: 'AF' },
  { name: 'Albania', flag: '🇦🇱', value: 'AL' },
  { name: 'Algeria', flag: '🇩🇿', value: 'DZ' },
  { name: 'Andorra', flag: '🇦🇩', value: 'AD' },
  { name: 'Angola', flag: '🇦🇴', value: 'AO' },
  { name: 'Antigua and Barbuda', flag: '🇦🇬', value: 'AG' },
  { name: 'Argentina', flag: '�🇷', value: 'AR' },
  { name: 'Armenia', flag: '🇦🇲', value: 'AM' },
  { name: 'Australia', flag: '🇦🇺', value: 'AU' },
  { name: 'Austria', flag: '🇦🇹', value: 'AT' },
  { name: 'Azerbaijan', flag: '🇦🇿', value: 'AZ' },
  { name: 'Bahamas', flag: '🇧🇸', value: 'BS' },
  { name: 'Bahrain', flag: '🇧🇭', value: 'BH' },
  { name: 'Bangladesh', flag: '🇧🇩', value: 'BD' },
  { name: 'Barbados', flag: '🇧🇧', value: 'BB' },
  { name: 'Belarus', flag: '🇧🇾', value: 'BY' },
  { name: 'Belgium', flag: '🇧🇪', value: 'BE' },
  { name: 'Belize', flag: '🇧🇿', value: 'BZ' },
  { name: 'Benin', flag: '🇧🇯', value: 'BJ' },
  { name: 'Bhutan', flag: '🇧🇹', value: 'BT' },
  { name: 'Bolivia', flag: '🇧🇴', value: 'BO' },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦', value: 'BA' },
  { name: 'Botswana', flag: '🇧🇼', value: 'BW' },
  { name: 'Brazil', flag: '🇧🇷', value: 'BR' },
  { name: 'Brunei Darussalam', flag: '🇧🇳', value: 'BN' },
  { name: 'Bulgaria', flag: '🇧🇬', value: 'BG' },
  { name: 'Burkina Faso', flag: '🇧🇫', value: 'BF' },
  { name: 'Burundi', flag: '🇧🇮', value: 'BI' },
  { name: 'Cabo Verde', flag: '🇨🇻', value: 'CV' },
  { name: 'Cambodia', flag: '🇰🇭', value: 'KH' },
  { name: 'Cameroon', flag: '🇨🇲', value: 'CM' },
  { name: 'Canada', flag: '🇨🇦', value: 'CA' },
  { name: 'Central African Republic', flag: '🇨🇫', value: 'CF' },
  { name: 'Chad', flag: '🇹🇩', value: 'TD' },
  { name: 'Chile', flag: '🇨🇱', value: 'CL' },
  { name: 'China', flag: '🇨🇳', value: 'CN' },
  { name: 'Colombia', flag: '🇨🇴', value: 'CO' },
  { name: 'Comoros', flag: '🇰🇲', value: 'KM' },
  { name: 'Congo, Democratic Republic of the', flag: '🇨🇩', value: 'CD' },
  { name: 'Congo', flag: '🇨🇬', value: 'CG' },
  { name: 'Costa Rica', flag: '🇨🇷', value: 'CR' },
  { name: 'Côte d\'Ivoire', flag: '🇨🇮', value: 'CI' },
  { name: 'Croatia', flag: '🇭🇷', value: 'HR' },
  { name: 'Cuba', flag: '🇨🇺', value: 'CU' },
  { name: 'Cyprus', flag: '🇨🇾', value: 'CY' },
  { name: 'Czechia', flag: '🇨🇿', value: 'CZ' },
  { name: 'Denmark', flag: '🇩🇰', value: 'DK' },
  { name: 'Djibouti', flag: '🇩🇯', value: 'DJ' },
  { name: 'Dominica', flag: '🇩🇲', value: 'DM' },
  { name: 'Dominican Republic', flag: '🇩🇴', value: 'DO' },
  { name: 'Ecuador', flag: '🇪🇨', value: 'EC' },
  { name: 'Egypt', flag: '🇪🇬', value: 'EG' },
  { name: 'El Salvador', flag: '🇸🇻', value: 'SV' },
  { name: 'Equatorial Guinea', flag: '🇬🇶', value: 'GQ' },
  { name: 'Eritrea', flag: '🇪🇷', value: 'ER' },
  { name: 'Estonia', flag: '🇪🇪', value: 'EE' },
  { name: 'Eswatini', flag: '🇸🇿', value: 'SZ' },
  { name: 'Ethiopia', flag: '🇪🇹', value: 'ET' },
  { name: 'Fiji', flag: '🇫🇯', value: 'FJ' },
  { name: 'Finland', flag: '🇫🇮', value: 'FI' },
  { name: 'France', flag: '🇫🇷', value: 'FR' },
  { name: 'Gabon', flag: '🇬🇦', value: 'GA' },
  { name: 'Gambia', flag: '🇬🇲', value: 'GM' },
  { name: 'Georgia', flag: '🇬🇪', value: 'GE' },
  { name: 'Germany', flag: '🇩🇪', value: 'DE' },
  { name: 'Ghana', flag: '🇬🇭', value: 'GH' },
  { name: 'Greece', flag: '🇬🇷', value: 'GR' },
  { name: 'Grenada', flag: '🇬🇩', value: 'GD' },
  { name: 'Guatemala', flag: '🇬🇹', value: 'GT' },
  { name: 'Guinea', flag: '🇬🇳', value: 'GN' },
  { name: 'Guinea-Bissau', flag: '🇬🇼', value: 'GW' },
  { name: 'Guyana', flag: '🇬🇾', value: 'GY' },
  { name: 'Haiti', flag: '🇭🇹', value: 'HT' },
  { name: 'Honduras', flag: '🇭🇳', value: 'HN' },
  { name: 'Hungary', flag: '🇭🇺', value: 'HU' },
  { name: 'Iceland', flag: '🇮🇸', value: 'IS' },
  { name: 'India', flag: '🇮🇳', value: 'IN' },
  { name: 'Indonesia', flag: '🇮🇩', value: 'ID' },
  { name: 'Iran', flag: '🇮🇷', value: 'IR' },
  { name: 'Iraq', flag: '🇮🇶', value: 'IQ' },
  { name: 'Ireland', flag: '🇮🇪', value: 'IE' },
  { name: 'Israel', flag: '🇮🇱', value: 'IL' },
  { name: 'Italy', flag: '🇮🇹', value: 'IT' },
  { name: 'Jamaica', flag: '🇯🇲', value: 'JM' },
  { name: 'Japan', flag: '🇯🇵', value: 'JP' },
  { name: 'Jordan', flag: '🇯🇴', value: 'JO' },
  { name: 'Kazakhstan', flag: '🇰🇿', value: 'KZ' },
  { name: 'Kenya', flag: '🇰🇪', value: 'KE' },
  { name: 'Kiribati', flag: '🇰🇮', value: 'KI' },
  { name: 'Kuwait', flag: '🇰🇼', value: 'KW' },
  { name: 'Kyrgyzstan', flag: '🇰🇬', value: 'KG' },
  { name: 'Laos', flag: '🇱🇦', value: 'LA' },
  { name: 'Latvia', flag: '🇱🇻', value: 'LV' },
  { name: 'Lebanon', flag: '🇱🇧', value: 'LB' },
  { name: 'Lesotho', flag: '🇱🇸', value: 'LS' },
  { name: 'Liberia', flag: '🇱🇷', value: 'LR' },
  { name: 'Libya', flag: '🇱🇾', value: 'LY' },
  { name: 'Liechtenstein', flag: '🇱🇮', value: 'LI' },
  { name: 'Lithuania', flag: '🇱🇹', value: 'LT' },
  { name: 'Luxembourg', flag: '🇱🇺', value: 'LU' },
  { name: 'Madagascar', flag: '🇲🇬', value: 'MG' },
  { name: 'Malawi', flag: '🇲🇼', value: 'MW' },
  { name: 'Malaysia', flag: '🇲🇾', value: 'MY' },
  { name: 'Maldives', flag: '🇲🇻', value: 'MV' },
  { name: 'Mali', flag: '🇲🇱', value: 'ML' },
  { name: 'Malta', flag: '🇲🇹', value: 'MT' },
  { name: 'Marshall Islands', flag: '🇲🇭', value: 'MH' },
  { name: 'Mauritania', flag: '🇲🇷', value: 'MR' },
  { name: 'Mauritius', flag: '🇲🇺', value: 'MU' },
  { name: 'Mexico', flag: '🇲🇽', value: 'MX' },
  { name: 'Micronesia', flag: '🇫🇲', value: 'FM' },
  { name: 'Moldova', flag: '🇲🇩', value: 'MD' },
  { name: 'Monaco', flag: '🇲🇨', value: 'MC' },
  { name: 'Mongolia', flag: '🇲🇳', value: 'MN' },
  { name: 'Montenegro', flag: '🇲🇪', value: 'ME' },
  { name: 'Morocco', flag: '🇲🇦', value: 'MA' },
  { name: 'Mozambique', flag: '🇲🇿', value: 'MZ' },
  { name: 'Myanmar', flag: '🇲🇲', value: 'MM' },
  { name: 'Namibia', flag: '🇳🇦', value: 'NA' },
  { name: 'Nauru', flag: '🇳🇷', value: 'NR' },
  { name: 'Nepal', flag: '🇳🇵', value: 'NP' },
  { name: 'Netherlands', flag: '🇳🇱', value: 'NL' },
  { name: 'New Zealand', flag: '🇳🇿', value: 'NZ' },
  { name: 'Nicaragua', flag: '🇳🇮', value: 'NI' },
  { name: 'Niger', flag: '🇳🇪', value: 'NE' },
  { name: 'Nigeria', flag: '🇳🇬', value: 'NG' },
  { name: 'North Korea', flag: '🇰🇵', value: 'KP' },
  { name: 'North Macedonia', flag: '🇲🇰', value: 'MK' },
  { name: 'Norway', flag: '🇳🇴', value: 'NO' },
  { name: 'Oman', flag: '🇴🇲', value: 'OM' },
  { name: 'Pakistan', flag: '🇵🇰', value: 'PK' },
  { name: 'Palau', flag: '🇵🇼', value: 'PW' },
  { name: 'Panama', flag: '🇵🇦', value: 'PA' },
  { name: 'Papua New Guinea', flag: '🇵🇬', value: 'PG' },
  { name: 'Paraguay', flag: '🇵🇾', value: 'PY' },
  { name: 'Peru', flag: '🇵🇪', value: 'PE' },
  { name: 'Philippines', flag: '🇵🇭', value: 'PH' },
  { name: 'Poland', flag: '🇵🇱', value: 'PL' },
  { name: 'Portugal', flag: '🇵🇹', value: 'PT' },
  { name: 'Qatar', flag: '🇶🇦', value: 'QA' },
  { name: 'Romania', flag: '🇷🇴', value: 'RO' },
  { name: 'Russia', flag: '🇷🇺', value: 'RU' },
  { name: 'Rwanda', flag: '🇷🇼', value: 'RW' },
  { name: 'Saint Kitts and Nevis', flag: '🇰🇳', value: 'KN' },
  { name: 'Saint Lucia', flag: '🇱🇨', value: 'LC' },
  { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', value: 'VC' },
  { name: 'Samoa', flag: '🇼🇸', value: 'WS' },
  { name: 'San Marino', flag: '🇸🇲', value: 'SM' },
  { name: 'Sao Tome and Principe', flag: '🇸🇹', value: 'ST' },
  { name: 'Saudi Arabia', flag: '🇸🇦', value: 'SA' },
  { name: 'Senegal', flag: '🇸🇳', value: 'SN' },
  { name: 'Serbia', flag: '🇷🇸', value: 'RS' },
  { name: 'Seychelles', flag: '🇸🇨', value: 'SC' },
  { name: 'Sierra Leone', flag: '🇸🇱', value: 'SL' },
  { name: 'Singapore', flag: '🇸🇬', value: 'SG' },
  { name: 'Slovakia', flag: '🇸🇰', value: 'SK' },
  { name: 'Slovenia', flag: '🇸🇮', value: 'SI' },
  { name: 'Solomon Islands', flag: '🇸🇧', value: 'SB' },
  { name: 'Somalia', flag: '🇸🇴', value: 'SO' },
  { name: 'South Africa', flag: '🇿🇦', value: 'ZA' },
  { name: 'South Korea', flag: '🇰🇷', value: 'KR' },
  { name: 'South Sudan', flag: '🇸🇸', value: 'SS' },
  { name: 'Spain', flag: '🇪🇸', value: 'ES' },
  { name: 'Sri Lanka', flag: '🇱🇰', value: 'LK' },
  { name: 'Sudan', flag: '🇸🇩', value: 'SD' },
  { name: 'Suriname', flag: '🇸🇷', value: 'SR' },
  { name: 'Sweden', flag: '🇸🇪', value: 'SE' },
  { name: 'Switzerland', flag: '🇨🇭', value: 'CH' },
  { name: 'Syria', flag: '🇸🇾', value: 'SY' },
  { name: 'Taiwan', flag: '🇹🇼', value: 'TW' },
  { name: 'Tajikistan', flag: '🇹🇯', value: 'TJ' },
  { name: 'Tanzania', flag: '🇹🇿', value: 'TZ' },
  { name: 'Thailand', flag: '🇹🇭', value: 'TH' },
  { name: 'Timor-Leste', flag: '🇹🇱', value: 'TL' },
  { name: 'Togo', flag: '🇹🇬', value: 'TG' },
  { name: 'Tonga', flag: '🇹🇴', value: 'TO' },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', value: 'TT' },
  { name: 'Tunisia', flag: '🇹🇳', value: 'TN' },
  { name: 'Turkey', flag: '🇹🇷', value: 'TR' },
  { name: 'Turkmenistan', flag: '🇹🇲', value: 'TM' },
  { name: 'Tuvalu', flag: '🇹🇻', value: 'TV' },
  { name: 'Uganda', flag: '🇺🇬', value: 'UG' },
  { name: 'Ukraine', flag: '🇺🇦', value: 'UA' },
  { name: 'United Arab Emirates', flag: '🇦🇪', value: 'AE' },
  { name: 'United Kingdom', flag: '🇬🇧', value: 'GB' },
  { name: 'United States', flag: '🇺🇸', value: 'US' },
  { name: 'Uruguay', flag: '🇺🇾', value: 'UY' },
  { name: 'Uzbekistan', flag: '🇺🇿', value: 'UZ' },
  { name: 'Vanuatu', flag: '🇻🇺', value: 'VU' },
  { name: 'Venezuela', flag: '🇻🇪', value: 'VE' },
  { name: 'Vietnam', flag: '🇻🇳', value: 'VN' },
  { name: 'Yemen', flag: '🇾🇪', value: 'YE' },
  { name: 'Zambia', flag: '🇿🇲', value: 'ZM' },
  { name: 'Zimbabwe', flag: '🇿🇼', value: 'ZW' },
];

export default countries;